<?php if (!empty($flash)) {
    print_r($flash);
} ?>

<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>

<table>
    <?php foreach ($users as $user): ?>
    <tr>
        <td>
            <?= $user['id'] ?>
        </td>
        <td>
            <a href="/users/show/<?= $user['id'] ?>"><?= $user['name'] ?></a>
        </td>
    </tr>
    <?php endforeach ?>
</table>